config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  resources :countries
  resources :error_logs
  resources :audit_logs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/error_log.rb
class ErrorLog < ApplicationRecord
end

app/controllers/error_logs_controller.rb
class ErrorLogsController < ApplicationController
  before_action :set_error_log, only: [:show, :edit, :update, :destroy]

  # GET /error_logs
  # GET /error_logs.json
  def index
    @error_logs = ErrorLog.all
  end

  # GET /error_logs/1
  # GET /error_logs/1.json
  def show
  end

  # GET /error_logs/new
  def new
    @error_log = ErrorLog.new
  end

  # GET /error_logs/1/edit
  def edit
  end

  # POST /error_logs
  # POST /error_logs.json
  def create
    @error_log = ErrorLog.new(error_log_params)

    respond_to do |format|
      if @error_log.save
        format.html { redirect_to @error_log, notice: 'Error log was successfully created.' }
        format.json { render :show, status: :created, location: @error_log }
      else
        format.html { render :new }
        format.json { render json: @error_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /error_logs/1
  # PATCH/PUT /error_logs/1.json
  def update
    respond_to do |format|
      if @error_log.update(error_log_params)
        format.html { redirect_to @error_log, notice: 'Error log was successfully updated.' }
        format.json { render :show, status: :ok, location: @error_log }
      else
        format.html { render :edit }
        format.json { render json: @error_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /error_logs/1
  # DELETE /error_logs/1.json
  def destroy
    @error_log.destroy
    respond_to do |format|
      format.html { redirect_to error_logs_url, notice: 'Error log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_error_log
      @error_log = ErrorLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def error_log_params
      params.require(:error_log).permit(:user_id, :user_type, :code, :message, :location, :status)
    end
end

app/helpers/error_logs_helper.rb
module ErrorLogsHelper
end

app/views/error_logs/_form.html.erb
<%= form_with(model: error_log, local: true) do |form| %>
  <% if error_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(error_log.errors.count, "error") %> prohibited this error_log from being saved:</h2>

      <ul>
      <% error_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_type %>
    <%= form.number_field :user_type %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/error_logs/edit.html.erb
<h1>Editing Error Log</h1>

<%= render 'form', error_log: @error_log %>

<%= link_to 'Show', @error_log %> |
<%= link_to 'Back', error_logs_path %>

app/views/error_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Error Logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User type</th>
      <th>Code</th>
      <th>Message</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @error_logs.each do |error_log| %>
      <tr>
        <td><%= error_log.user_id %></td>
        <td><%= error_log.user_type %></td>
        <td><%= error_log.code %></td>
        <td><%= error_log.message %></td>
        <td><%= error_log.location %></td>
        <td><%= error_log.status %></td>
        <td><%= link_to 'Show', error_log %></td>
        <td><%= link_to 'Edit', edit_error_log_path(error_log) %></td>
        <td><%= link_to 'Destroy', error_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Error Log', new_error_log_path %>

app/views/error_logs/new.html.erb
<h1>New Error Log</h1>

<%= render 'form', error_log: @error_log %>

<%= link_to 'Back', error_logs_path %>

app/views/error_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @error_log.user_id %>
</p>

<p>
  <strong>User type:</strong>
  <%= @error_log.user_type %>
</p>

<p>
  <strong>Code:</strong>
  <%= @error_log.code %>
</p>

<p>
  <strong>Message:</strong>
  <%= @error_log.message %>
</p>

<p>
  <strong>Location:</strong>
  <%= @error_log.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @error_log.status %>
</p>

<%= link_to 'Edit', edit_error_log_path(@error_log) %> |
<%= link_to 'Back', error_logs_path %>