config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  resources :countries
  resources :error_logs
  resources :audit_logs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
end

app/controllers/audit_logs_controller.rb
class AuditLogsController < ApplicationController
  before_action :set_audit_log, only: [:show, :edit, :update, :destroy]

  # GET /audit_logs
  # GET /audit_logs.json
  def index
    @audit_logs = AuditLog.all
  end

  # GET /audit_logs/1
  # GET /audit_logs/1.json
  def show
  end

  # GET /audit_logs/new
  def new
    @audit_log = AuditLog.new
  end

  # GET /audit_logs/1/edit
  def edit
  end

  # POST /audit_logs
  # POST /audit_logs.json
  def create
    @audit_log = AuditLog.new(audit_log_params)

    respond_to do |format|
      if @audit_log.save
        format.html { redirect_to @audit_log, notice: 'Audit log was successfully created.' }
        format.json { render :show, status: :created, location: @audit_log }
      else
        format.html { render :new }
        format.json { render json: @audit_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audit_logs/1
  # PATCH/PUT /audit_logs/1.json
  def update
    respond_to do |format|
      if @audit_log.update(audit_log_params)
        format.html { redirect_to @audit_log, notice: 'Audit log was successfully updated.' }
        format.json { render :show, status: :ok, location: @audit_log }
      else
        format.html { render :edit }
        format.json { render json: @audit_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audit_logs/1
  # DELETE /audit_logs/1.json
  def destroy
    @audit_log.destroy
    respond_to do |format|
      format.html { redirect_to audit_logs_url, notice: 'Audit log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audit_log
      @audit_log = AuditLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audit_log_params
      params.require(:audit_log).permit(:user_id, :user_type, :trace_id, :action_type, :action_meta, :ip)
    end
end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/views/audit_logs/_form.html.erb
<%= form_with(model: audit_log, local: true) do |form| %>
  <% if audit_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(audit_log.errors.count, "error") %> prohibited this audit_log from being saved:</h2>

      <ul>
      <% audit_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_type %>
    <%= form.number_field :user_type %>
  </div>

  <div class="field">
    <%= form.label :trace_id %>
    <%= form.text_field :trace_id %>
  </div>

  <div class="field">
    <%= form.label :action_type %>
    <%= form.text_field :action_type %>
  </div>

  <div class="field">
    <%= form.label :action_meta %>
    <%= form.text_field :action_meta %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/audit_logs/edit.html.erb
<h1>Editing Audit Log</h1>

<%= render 'form', audit_log: @audit_log %>

<%= link_to 'Show', @audit_log %> |
<%= link_to 'Back', audit_logs_path %>

app/views/audit_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Audit Logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User type</th>
      <th>Trace</th>
      <th>Action type</th>
      <th>Action meta</th>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @audit_logs.each do |audit_log| %>
      <tr>
        <td><%= audit_log.user_id %></td>
        <td><%= audit_log.user_type %></td>
        <td><%= audit_log.trace_id %></td>
        <td><%= audit_log.action_type %></td>
        <td><%= audit_log.action_meta %></td>
        <td><%= audit_log.ip %></td>
        <td><%= link_to 'Show', audit_log %></td>
        <td><%= link_to 'Edit', edit_audit_log_path(audit_log) %></td>
        <td><%= link_to 'Destroy', audit_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audit Log', new_audit_log_path %>

app/views/audit_logs/new.html.erb
<h1>New Audit Log</h1>

<%= render 'form', audit_log: @audit_log %>

<%= link_to 'Back', audit_logs_path %>

app/views/audit_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @audit_log.user_id %>
</p>

<p>
  <strong>User type:</strong>
  <%= @audit_log.user_type %>
</p>

<p>
  <strong>Trace:</strong>
  <%= @audit_log.trace_id %>
</p>

<p>
  <strong>Action type:</strong>
  <%= @audit_log.action_type %>
</p>

<p>
  <strong>Action meta:</strong>
  <%= @audit_log.action_meta %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @audit_log.ip %>
</p>

<%= link_to 'Edit', edit_audit_log_path(@audit_log) %> |
<%= link_to 'Back', audit_logs_path %>