config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  resources :countries
  resources :error_logs
  resources :audit_logs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  before_create :set_user_data
  def set_user_data
    self.account_number = "YP" + rand(00000000..99999999).to_s
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create, :homepage]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :phone, :account_number, :language, :country_id, :status, :verified, :locked, :failed_attempts, :active_otp, :otp_secret_key)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :account_number %>
    <%= form.text_field :account_number %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.number_field :country_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :verified %>
    <%= form.check_box :verified %>
  </div>

  <div class="field">
    <%= form.label :locked %>
    <%= form.check_box :locked %>
  </div>

  <div class="field">
    <%= form.label :failed_attempts %>
    <%= form.number_field :failed_attempts %>
  </div>

  <div class="field">
    <%= form.label :active_otp %>
    <%= form.number_field :active_otp %>
  </div>

  <div class="field">
    <%= form.label :otp_secret_key %>
    <%= form.text_field :otp_secret_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/homepage.html.erb
<h2>Yalla Pay</h2>

<%= link_to 'users', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Phone</th>
      <th>Account number</th>
      <th>Language</th>
      <th>Country</th>
      <th>Status</th>
      <th>Verified</th>
      <th>Locked</th>
      <th>Failed attempts</th>
      <th>Active otp</th>
      <th>Otp secret key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.phone %></td>
        <td><%= user.account_number %></td>
        <td><%= user.language %></td>
        <td><%= user.country_id %></td>
        <td><%= user.status %></td>
        <td><%= user.verified %></td>
        <td><%= user.locked %></td>
        <td><%= user.failed_attempts %></td>
        <td><%= user.active_otp %></td>
        <td><%= user.otp_secret_key %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.select(:country_id,  options_for_select(Country.all.collect {|p| [ p.full_name, p.id ] } ) ,{} ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @user.account_number %>
</p>

<p>
  <strong>Language:</strong>
  <%= @user.language %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @user.verified %>
</p>

<p>
  <strong>Locked:</strong>
  <%= @user.locked %>
</p>

<p>
  <strong>Failed attempts:</strong>
  <%= @user.failed_attempts %>
</p>

<p>
  <strong>Active otp:</strong>
  <%= @user.active_otp %>
</p>

<p>
  <strong>Otp secret key:</strong>
  <%= @user.otp_secret_key %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>