config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  resources :countries
  resources :error_logs
  resources :audit_logs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:full_name, :short_code, :phone_code, :status)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :short_code %>
    <%= form.text_field :short_code %>
  </div>

  <div class="field">
    <%= form.label :phone_code %>
    <%= form.text_field :phone_code %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Short code</th>
      <th>Phone code</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.full_name %></td>
        <td><%= country.short_code %></td>
        <td><%= country.phone_code %></td>
        <td><%= country.status %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @country.full_name %>
</p>

<p>
  <strong>Short code:</strong>
  <%= @country.short_code %>
</p>

<p>
  <strong>Phone code:</strong>
  <%= @country.phone_code %>
</p>

<p>
  <strong>Status:</strong>
  <%= @country.status %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>